package escalima

/**
  * The exception thrown by either of the parse methods in ECMAScript if esprima was not able to parse the JavaScript source.
  *
  * @param message Error message generated by esprima
  */
case class ESPrimaParseException(message: String) extends Exception(message)
